### ISSUE TITLE
`terraform destroy` leaves behind resources after a failed `terraform apply`

### ISSUE THREAD

**Issue by clnperez** [ocp-power-automation/ocp4-upi-powervs#73]
After a cluster creation attempt that fails, I've seen the `terraform destroy` command complete but still leave behind instances and volumes. The scenario seems to be that the cluster creation is attempted, instances are created, but never boot. The instances created include the bastion, bootstrap, workers, and masters. All of these are left behind in the case that none of them come up.

**Comment by bpradipt** [comment]
@yussufsh would you be able to take a look at it later on ?

**Comment by yussufsh** [comment]
Whatever is created by TF will be deleted when destroy is completed successfully.
Even when a resource is destroyed manually (via UI) TF needs to know the resource status. This can be done via `terraform state rm <resource_addr>` command. Subsequent apply will create the missing resource for you.
Another scenario is when you cancel the TF run (hitting ctrl+C OR network disconnect to the terminal OR process crash) TF won't know the status of the resource it was created during the breakdown. Here the way to recover is to import the resource into tfstate by running `terraform import <resource_addr> <resource_id>` so that TF will delete it when the destroy command is run.


With the above explanation, I think it is good to close this issue.

**Comment by bpradipt** [comment]
@yussufsh can we add some concrete examples to https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/master/docs/known_issues.md

**Comment by yussufsh** [comment]
May be create an issue and I can (or someone can help) work on providing the examples.
